<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SterlingVale.Application.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SterlingVale.Application\SterlingVale.Application.csproj" />
    <ProjectReference Include="..\..\src\SterlingVale.DataGenerator\SterlingVale.DataGenerator.csproj" />
  </ItemGroup>

</Project>
